** TODO [31/37]
   - [X] Create UI for authentication : /auth/login, /auth/register, /auth/logout
   - [X] Create a navigation bar
   - [X] Create a layout for landing page, and for user profile
   - [X] Fix tailwind warning
   - [X] Create navigation for major areas
     - [X] Editor (adventures)
   - [X] Add leaflet to User profile page
   - [X] Add adventure creation interface
   - [X] Add call to get adventures from api
   - [ ] Fix burger navbar
   - [X] Create second navbar for editor, visible upon adv creation and selection.
   - [X] Create navigation for Map editor, Blog Editor, gear editor.
   - [X] Add a map on Map editor page
   - [X] Change style of nav items -- sync them, and show selected.
   - [X] Decide whether or not to replicate multiple map or just 1 per adventure -- keep multiple
   - [X] Hide 'Create' button on map editor page as needed
   - [X] Hide second nav bar as needed
   - [X] Create a data binding for new map name and a method binding for create click
   - [X] Do async map fetch on page load... save to store? (not saving for store now)
   - [X] Track selected map, and change its style... on map editor page
   - [X] Create UI for map segment creation.
     - [X] Create layers for path, newPath, startMarker, endMarker
     - [X] on first click -> draw startMarker, on second click -> draw endMarker, and a line between them.
     - [X] on 'save segment' click send post
   - [X] on map editor page -> Reload map on map change.
   - [X] On map editor page -> set view on current map.
   - [X] Hide segment creation if there is no map  created.
   - [X] Disable segment drawing if there is no map selected.
   - [X] Center map on meaningful location if there is no maps with coordinates...
   - [X] When deleting a map, might have to clearLayers() and unset start and endoint
   - [X] When creating a map, also need to clear layers...
   - [X] Add a datetime picker for segment start and end point.
   - [X] Show new segment distance.
   - [X] Set guessed start and end time automatically.
   - [X] Add a photo editor page.
   - [ ] Get photo upload payload from vuex
   - [X] Fetch all maps in one request, store in vuex.
   - [ ] When deleting currently selected map, reload startpoint afterward from newly selected segment.
   - [ ] Create nicer looking login and registration pages.
   - [ ] Create a lotout button.
   - [ ] Let the user know that a map must be created before photos can be uploaded.

** BUGS [5/7]
   - [X] On Adventure delete, stop signal propogation to avoid changing selected adventure
   - [X] On adventure delete, if current adventure gets moved, need to adjust
   - [X] On map delete, also might need to change selected and load and hide layers
   - [X] on map editor page -> init a geojson so that segment creation will be possible for first map
   - [ ] On logout, check the console error about error 404 from backend
   - [X] map editor fails to load when there are no coordinates in the map.
   - [ ] Assign maps and activeMapIndex at the time when adventures are loaded... this way I can visit photo editor without having to go to map editor first.

** CSS [0/3]
   - [ ] In editor - on the first nav bar, if adventure editor is active, the highlight doesn't go all the way to top and bottom
   - [ ] Get datetimepicker to look like the rest of the site.
   - [ ] Date-time-picker colides with leaflet zoom controls.
   - [ ] Hide map when there are no maps.

