** TODO [16/20]
   - [X] Create UI for authentication : /auth/login, /auth/register, /auth/logout
   - [X] Create a navigation bar
   - [X] Create a layout for landing page, and for user profile
   - [X] Fix tailwind warning
   - [X] Create navigation for major areas
     - [X] Editor (adventures)
   - [X] Add leaflet to User profile page
   - [X] Add adventure creation interface
   - [X] Add call to get adventures from api
   - [ ] Fix burger navbar
   - [X] Create second navbar for editor, visible upon adv creation and selection.
   - [X] Create navigation for Map editor, Blog Editor, gear editor.
   - [X] Add a map on Map editor page
   - [X] Change style of nav items -- sync them, and show selected.
   - [X] Decide whether or not to replicate multiple map or just 1 per adventure -- keep multiple
   - [ ] Hide 'Create' button on map editor page as needed
   - [ ] Hide second nav bar as needed
   - [X] Create a data binding for new map name and a method binding for create click
   - [X] Do async map fetch on page load... save to store? (not saving for store now)
   - [X] Track selected map, and change its style... on map editor page
   - [ ] Create UI for map segment creation.

** BUGS [1/2]
   - [X] On Adventure delete, stop signal propogation to avoid changing selected adventure
   - [ ] On adventure delete, if current adventure gets moved, need to adjust
   - [ ] In editor - on the first nav bar, if adventure editor is active, the highlight doesn't go all the way to top and bottom
